
name: string_art_generator
description: A Flutter app to generate photorealistic string art designs.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.0
  flutter_svg: ^1.1.6
  file_picker: ^5.2.2
  path_provider: ^2.0.12
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
